AWSTemplateFormatVersion: '2010-09-09'
Description: "ANOTHER new Simple S3 bucket I am new"

Parameters:
  BucketName:
    Type: String
    Description: "Name of the S3 bucket"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  BucketName:
    Description: "Created S3 bucket name"
    Value: !Ref S3Bucket


